apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scanner-deployment
  namespace: restricted
  labels:
    app: kube-scanner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-scanner
  template:
    metadata:
      labels:
        app: kube-scanner
    spec:
      containers:
      - name: kube-scanner
        image: achebeh/factual:latest
        ports:
        - containerPort: 8081
