apiVersion: v1
kind: Service
metadata:
  name: kube-scanner-service
  namespace: restricted
spec:
  selector:
    app: kube-scanner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort